### PR TITLE
Add WEMOS 8266 board and case

### PR DESCRIPTION
**Pull request by kortschak**
Please take a look.

### CODE REVIEW

**Comment by ubitux** [comment]
Hi,

Thanks for the clean submission. I have a few initial questions/requests:

- do you have a photo of the board with and without the printed case? I'm asking because i was under the impression that the board was kind of flipped, and it would have make more sense for the case if it was the other way around
- please fix the copyright (fix the date + use your name)
- you have an invalid `rot=...` as argument to `button()`
- what 3D printer did you use to print, did it come out nice?

**Comment by kortschak** [comment]
I can provide a photo of a board out of the case and a board in a case. The orientation of the board in the case made the most sense for keeping the CPU near the vent and providing a space for the USB socket port. I'll organise photos tomorrow.

I've fixed the copyright headers and removed the rot arg.

The case was printed on a Prusa i3 Mk3 and came out nicely. The only issue is that the screw holes in the board are really smaller than is reasonable for the printer to get good pins for, but they work well enough.

**Comment by kortschak** [comment]
I don't have a WEMOS board without header pins, so these will have to do. In the first two photos the board is oriented as it is in the case (apologies for the lighting).

img_20181111_080519746

img_20181111_080541618

When you look down the USB port it looks like there is a lot of room in the case (there is), but this lets the plug fit within the height of the case.

img_20181111_080644154

**Comment by kortschak** [comment]
*ping*

**Comment by ubitux** [comment]
Sorry I forgot to merge this. I just looked at it again and spot something: would you mind dropping the old board scad from the first commit (the electronics one).

Also, it would be nice to add the pins to the board at some point.

**Comment by kortschak** [comment]
Sorry, I don't understand which board you are talking about. Would you post a comment against the file explaining?

**Comment by ubitux** [comment]
> Sorry, I don't understand which board you are talking about. Would you post a comment against the file explaining?

In 6ae2367cb9bbf27758011c12ef04c321c20d4850, you're adding `electronics/wemos_esp8266.scad`, which looks like an old version of the file `boards/wemos_esp8266.scad` you add in a later commit.

**Comment by kortschak** [comment]
Thanks. Fixed.

**Comment by ubitux** [comment]
Pushed. The gif and README needs updating but since the electronics components submitted are not finished, I'd rather not.

**Pull request merged**
